### ISSUE TITLE
NPE with `$` in spark sql tests

### ISSUE THREAD

**Issue by Bunyod** [yaravind/learn-spark#1]
But doesn't work if I use $ method call to reference the columns as shown below
```
def toWords(linesDf: DataFrame) = {
    import spark.implicits._
    linesDf
        .select($"line"),
            explode(split($"line", WhitespaceRegex)).as("word"))
}
```

**Comment by Bunyod** [comment]
Can you try to replace toWords method and re-run this:
```
  def toWords(linesDf: DataFrame) = {
    import spark.sqlContext.implicits._
    linesDf
      .select($"line", explode(split($"line", WhitespaceRegex).as("word")))
  }
```

I'm getting NPE because of version incompatibilities. I have now several versions of the same libraries

**Comment by yaravind** [comment]
@Bunyod Tried but getting the same exception

java.lang.NullPointerException was thrown.
java.lang.NullPointerException
	at com.aravind.oss.eg.wordcount.spark.WordCountDFApp$.toWords(WordCountDFApp.scala:41)
	at com.aravind.oss.eg.wordcount.spark.WordCountDFAppTestSpec$$anonfun$1.apply$mcV$sp(WordCountDFAppTestSpec.scala:34)
	at com.aravind.oss.eg.wordcount.spark.WordCountDFAppTestSpec$$anonfun$1.apply(WordCountDFAppTestSpec.scala:23)
	at com.aravind.oss.eg.wordcount.spark.WordCountDFAppTestSpec$$anonfun$1.apply(WordCountDFAppTestSpec.scala:23)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:393)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:381)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:370)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:407)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:381)

**Comment by Bunyod** [comment]
This is really strange we are getting different NPEs:

> java.lang.NullPointerException
at com.aravind.oss.eg.wordcount.spark.WordCountDFApp$.toWords(WordCountDFApp.scala:43)
	at com.aravind.oss.eg.wordcount.spark.WordCountDFAppTestSpec.$anonfun$new$1(WordCountDFAppTestSpec.scala:32)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

**Comment by Bunyod** [comment]
There is something odd with one of the lib, but I'm not sure:
```

  def toWords(linesDf: DataFrame) = {
    import spark.sqlContext.implicits._
    linesDf
      .select(
        linesDf("line"),
        explode(split(linesDf("line"), WhitespaceRegex).as("word"))
      )
  }
```
Also gives an error:

> 	at com.github.mrpowers.spark.fast.tests.DatasetComparer.assertSmallDatasetEquality(DatasetComparer.scala:108)
	at com.github.mrpowers.spark.fast.tests.DatasetComparer.assertSmallDatasetEquality$(DatasetComparer.scala:94)
	at com.aravind.oss.eg.wordcount.spark.WordCountDFAppTestSpec.assertSmallDatasetEquality(WordCountDFAppTestSpec.scala:12)
	at com.aravind.oss.eg.wordcount.spark.WordCountDFAppTestSpec.$anonfun$new$1(WordCountDFAppTestSpec.scala:34)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:

**Comment by Bunyod** [comment]
Maybe it's related with java version. Because I don't use java8

**Comment by yaravind** [comment]
The code has a dependency on Java 8

**Comment by yaravind** [comment]
Fixed the issue based on update from https://stackoverflow.com/questions/61166287/nullpointerexception-when-referencing-dataframe-column-names-with-method-call/61170741#61170741
